apiVersion: v1
kind: Service
metadata:
  name: %{DKI_SERVICE_NAME}
  labels:
    app: %{DKI_SERVICE_NAME}
spec:
  type: NodePort
  ports:
  - port: %{PORT}
    name: http
  selector:
    app: %{DKI_SERVICE_NAME}
